### ISSUE TITLE
Import-error limitation

### ISSUE THREAD

**Issue by DavidEBest** [mikebryant/codeclimate-pylint#2]
This looks great!

I'm not sure I follow your reasoning behind disabling the `import-error` test. Pylint normally works without a network connection, why does that limitation keep it from functioning in a CodeClimate engine?

**Comment by mikebryant** [comment]
The only files accessible at analysis time are the ones in the git repository. To analyse a python project, I would normally install all of the dependencies, and then run pylint.

At this point in time, the codeclimate engine doesn't support network access (https://github.com/codeclimate/spec/blob/master/SPEC.md#security-restrictions), so installing the dependencies from pip using setup.py / requirements.txt isn't possible.

So any project which has dependencies ends up with lots of warnings about import errors, as pylint is unable to import those dependencies during analysis.

-- that was my reasoning anyway. Have I missed something?

**Comment by DavidEBest** [comment]
That totally makes sense if the tool is running on the CC Platform. If I run it against my development directory, I expected it to have access to the dependencies I already have installed.

Looking back, I think that expectation probably isn't reasonable. :)

**Comment by mikebryant** [comment]
ahh, I see where you're coming from.
It's still isolated in docker - if you had the dependencies in the working directory, they'd get pulled into the available files during analysis, but it still wouldn't have the environment settings to look for them. (And I always use `virtualenvwrapper`, so they're not in the same directory anyway).. Would be tricky to support.

I've been informed that CC will be allowing network access eventually, when they've solved some of the security issues. When that happens it'll be available locally too.

My inclination right now is to leave it matching the deployed version, so there's less differences between a local run and one on the platform.

Happy to accept pull requests though, if you think it can be implemented cleanly

**Comment by DavidEBest** [comment]
Not sure it can be done cleanly, and I agree that it'd be good to keep the local results similar to the CC platform results.

Thanks for humoring me. :)
