### ISSUE TITLE
Codeclimate-pylint engine

### ISSUE THREAD

**Issue by larkinscott** [mikebryant/codeclimate-pylint#4]
Hey @mikebryant! 

I'm the Open Source Evangelist at Code Climate. Just wanted to say "hi" and see if we can help you with continuing progress on your Pylint engine. Looks awesome and would love to get it into beta! 

Here's a link to our Developer Program (https://codeclimate.com/dev_form). I know you were in touch with MRB previously, but since he's no longer with Code Climate, I'm copying in @dblandin.

Let me know if there's anything we can do!

**Comment by adriankrupa** [comment]
Hey @larkinscott @mikebryant 
Any news here? Are you working on that?

**Comment by g13013** [comment]
Any news on that ?

**Comment by pawamoy** [comment]
:up:

**Comment by dblandin** [comment]
@patrys recently expressed interest in building a pylint engine via the codeclimate-community slack org. This would be a great place to start!

**Comment by patrys** [comment]
@dblandin I'll take a look once we're done with `isort`.

**Comment by caiofbpa** [comment]
I have built a working pylint engine at https://github.com/meuspedidos/codeclimate-pylint

If anyone wants to test it or use it, feel free.

@larkinscott I've signed up for the CC Developer Program already, but I'm yet to be contacted regarding what needs to be done to include my version of the pylint engine in the list of officially supported engines.

**Comment by larkinscott** [comment]
Thanks @caiofbpa! I'll take a look at this now and follow up with you re: next steps.

**Comment by mikebryant** [comment]
Sorry for the lack of updates, this got deprioritised internally and I've been busy with other things.

@caiofbpa Thanks for picking this up!

**Comment by caiofbpa** [comment]
To avoid spamming this issue, I've created a new one on the new repo: https://github.com/meuspedidos/codeclimate-pylint/issues/1

@larkinscott, shall we continue the conversation over there? Any news about the next steps? 

Thanks @mikebryant for the initial work on this engine.
